apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: homelab
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
              name: http
            - containerPort: 8920
              name: https
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: "http://media.homelab.home.arpa"
          volumeMounts:
            - name: media-general
              mountPath: /media/General
            - name: media-extension2
              mountPath: /media/Extension2
            - name: media-general2
              mountPath: /media/General2
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 2Gi
      volumes:
        - name: media-general
          hostPath:
            path: /mnt/wdex4100/General/Media
            type: DirectoryOrCreate
        - name: media-extension2
          hostPath:
            path: /mnt/wdex4100/Extension2/Media
            type: DirectoryOrCreate
        - name: media-general2
          hostPath:
            path: /mnt/wdex4100/General2/Media
            type: DirectoryOrCreate
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: homelab
  labels:
    app: jellyfin
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
