apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-ingress
  namespace: homelab
spec:
  ingressClassName: nginx
  rules:
    - host: stock-ez.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-ez
                port:
                  number: 80
    - host: dashboard.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homelab-dashboard
                port:
                  number: 80
    - host: portainer.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 9000
